use super::{assert_contains, assert_contains_case_insensitive, read_repo_file, repo_root};

#[test]
fn support_claim_source_docs_exist_and_are_linked() {
    let readme = read_repo_file("README.md");
    let todos = read_repo_file("TODOS.md");
    let broker_contract = read_repo_file("docs/codexw-broker-adapter-contract.md");
    let broker_status = read_repo_file("docs/codexw-broker-adapter-status.md");
    let broker_client_policy = read_repo_file("docs/codexw-broker-client-policy.md");
    let broker_out_of_scope = read_repo_file("docs/codexw-broker-out-of-scope.md");
    let broker_endpoint_audit = read_repo_file("docs/codexw-broker-endpoint-audit.md");
    let broker_proof = read_repo_file("docs/codexw-broker-proof-matrix.md");
    let broker_policy = read_repo_file("docs/codexw-broker-support-policy.md");
    let broker_hardening = read_repo_file("docs/codexw-broker-hardening-catalog.md");
    let broker_decision = read_repo_file("docs/codexw-broker-connector-decision.md");
    let broker_promotion = read_repo_file("docs/codexw-broker-adapter-promotion.md");
    let broker_mapping = read_repo_file("docs/codexw-broker-connector-mapping.md");
    let broker_compat_target = read_repo_file("docs/codexw-broker-compatibility-target.md");
    let broker_adapter_plan = read_repo_file("docs/codexw-broker-connector-adapter-plan.md");
    let broker_shared_assumptions = read_repo_file("docs/codexw-broker-shared-assumptions.md");
    let broker_session_identity = read_repo_file("docs/codexw-broker-session-identity.md");
    let broker_event_envelope = read_repo_file("docs/codexw-broker-event-envelope.md");
    let native_boundaries = read_repo_file("docs/codexw-native-support-boundaries.md");
    let native_status = read_repo_file("docs/codexw-native-product-status.md");
    let native_proof = read_repo_file("docs/codexw-native-proof-matrix.md");
    let native_policy = read_repo_file("docs/codexw-native-support-policy.md");
    let native_hardening = read_repo_file("docs/codexw-native-hardening-catalog.md");
    let self_evolution = read_repo_file("docs/codexw-self-evolution.md");
    let self_evolution_plan = read_repo_file("docs/codexw-self-evolution-implementation-plan.md");
    let self_supervision = read_repo_file("docs/codexw-self-supervision.md");
    let self_supervision_plan =
        read_repo_file("docs/codexw-self-supervision-implementation-plan.md");
    let background_execution_boundary =
        read_repo_file("docs/codexw-background-execution-boundary.md");
    let plugin_system = read_repo_file("docs/codexw-plugin-system.md");
    let plugin_system_plan = read_repo_file("docs/codexw-plugin-system-implementation-plan.md");
    let local_api_sketch = read_repo_file("docs/codexw-local-api-sketch.md");
    let local_api_plan = read_repo_file("docs/codexw-local-api-implementation-plan.md");
    let local_api_route_matrix = read_repo_file("docs/codexw-local-api-route-matrix.md");
    let local_api_event_sourcing = read_repo_file("docs/codexw-local-api-event-sourcing.md");
    let broker_host_matrix = read_repo_file("docs/codexw-broker-host-examination-matrix.md");
    let cross_deployment = read_repo_file("docs/codexw-cross-deployment-collaboration.md");
    let cross_project_dependency =
        read_repo_file("docs/codexw-cross-project-dependency-collaboration.md");
    let cross_project_contract =
        read_repo_file("docs/codexw-cross-project-dependency-contract-sketch.md");
    let cross_project_plan =
        read_repo_file("docs/codexw-cross-project-dependency-implementation-plan.md");
    let cross_deployment_contract =
        read_repo_file("docs/codexw-cross-deployment-handoff-contract-sketch.md");
    let cross_deployment_plan =
        read_repo_file("docs/codexw-cross-deployment-handoff-implementation-plan.md");
    let broker_artifact_sketch = read_repo_file("docs/codexw-broker-artifact-contract-sketch.md");
    let broker_artifact_plan = read_repo_file("docs/codexw-broker-artifact-implementation-plan.md");
    let workspace_policy = read_repo_file("docs/codexw-workspace-tool-policy.md");
    let broker_client_arch = read_repo_file("docs/codexw-broker-client-architecture.md");
    let broker_client_fixture = read_repo_file("docs/codexw-broker-client-fixture.md");
    let broker_handoff = read_repo_file("docs/codexw-broker-integration-handoff.md");
    let checklist = read_repo_file("docs/codexw-support-claim-checklist.md");

    for file in [
        "docs/codexw-broker-adapter-contract.md",
        "docs/codexw-broker-adapter-status.md",
        "docs/codexw-broker-client-policy.md",
        "docs/codexw-broker-out-of-scope.md",
        "docs/codexw-broker-proof-matrix.md",
        "docs/codexw-broker-support-policy.md",
        "docs/codexw-broker-hardening-catalog.md",
        "docs/codexw-broker-connector-decision.md",
        "docs/codexw-broker-compatibility-target.md",
        "docs/codexw-broker-connector-adapter-plan.md",
        "docs/codexw-broker-shared-assumptions.md",
        "docs/codexw-broker-session-identity.md",
        "docs/codexw-broker-event-envelope.md",
        "docs/codexw-native-support-boundaries.md",
        "docs/codexw-native-product-status.md",
        "docs/codexw-native-proof-matrix.md",
        "docs/codexw-native-support-policy.md",
        "docs/codexw-native-hardening-catalog.md",
        "docs/codexw-self-evolution.md",
        "docs/codexw-self-evolution-implementation-plan.md",
        "docs/codexw-self-supervision.md",
        "docs/codexw-self-supervision-implementation-plan.md",
        "docs/codexw-background-execution-boundary.md",
        "docs/codexw-plugin-system.md",
        "docs/codexw-plugin-system-implementation-plan.md",
        "docs/codexw-local-api-sketch.md",
        "docs/codexw-local-api-implementation-plan.md",
        "docs/codexw-local-api-route-matrix.md",
        "docs/codexw-local-api-event-sourcing.md",
        "docs/codexw-broker-client-architecture.md",
        "docs/codexw-cross-deployment-collaboration.md",
        "docs/codexw-cross-project-dependency-collaboration.md",
        "docs/codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-cross-project-dependency-implementation-plan.md",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
        "docs/codexw-broker-client-fixture.md",
        "docs/codexw-broker-host-examination-matrix.md",
        "docs/codexw-broker-integration-handoff.md",
        "docs/codexw-broker-artifact-contract-sketch.md",
        "docs/codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-workspace-tool-policy.md",
        "docs/codexw-support-claim-checklist.md",
    ] {
        let path = repo_root().join(file);
        assert!(path.exists(), "expected {} to exist", path.display());
    }

    assert_contains(
        &readme,
        "docs/codexw-broker-adapter-contract.md",
        "README.md",
    );
    assert_contains(&readme, "docs/codexw-broker-adapter-status.md", "README.md");
    assert_contains(&readme, "docs/codexw-broker-client-policy.md", "README.md");
    assert_contains(&readme, "docs/codexw-broker-out-of-scope.md", "README.md");
    assert_contains(&readme, "docs/codexw-broker-proof-matrix.md", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-broker-client-architecture.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-deployment-collaboration.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-project-dependency-collaboration.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-project-dependency-contract-sketch.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-project-dependency-implementation-plan.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-broker-host-examination-matrix.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-broker-integration-handoff.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-broker-artifact-contract-sketch.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-broker-artifact-implementation-plan.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-broker-hardening-catalog.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-native-support-boundaries.md",
        "README.md",
    );
    assert_contains(&readme, "docs/codexw-native-product-status.md", "README.md");
    assert_contains(&readme, "docs/codexw-native-proof-matrix.md", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-native-hardening-catalog.md",
        "README.md",
    );
    assert_contains(&readme, "docs/codexw-self-evolution.md", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-self-evolution-implementation-plan.md",
        "README.md",
    );
    assert_contains(&readme, "docs/codexw-self-supervision.md", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-self-supervision-implementation-plan.md",
        "README.md",
    );
    assert_contains(
        &readme,
        "docs/codexw-background-execution-boundary.md",
        "README.md",
    );
    assert_contains(&readme, "docs/codexw-plugin-system.md", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-plugin-system-implementation-plan.md",
        "README.md",
    );
    assert_contains(&readme, "no longer advertised by default", "README.md");
    assert_contains(
        &readme,
        "docs/codexw-support-claim-checklist.md",
        "README.md",
    );

    assert_contains(&todos, "docs/codexw-broker-adapter-contract.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-broker-adapter-status.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-broker-client-policy.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-broker-out-of-scope.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-broker-proof-matrix.md", "TODOS.md");
    assert_contains(
        &todos,
        "docs/codexw-broker-client-architecture.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-deployment-collaboration.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-project-dependency-collaboration.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-project-dependency-contract-sketch.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-project-dependency-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-broker-host-examination-matrix.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-broker-integration-handoff.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-broker-artifact-contract-sketch.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-broker-artifact-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-broker-hardening-catalog.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-native-support-boundaries.md",
        "TODOS.md",
    );
    assert_contains(&todos, "docs/codexw-native-product-status.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-native-proof-matrix.md", "TODOS.md");
    assert_contains(
        &todos,
        "docs/codexw-native-hardening-catalog.md",
        "TODOS.md",
    );
    assert_contains(&todos, "docs/codexw-self-evolution.md", "TODOS.md");
    assert_contains(
        &todos,
        "docs/codexw-self-evolution-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(&todos, "docs/codexw-self-supervision.md", "TODOS.md");
    assert_contains(
        &todos,
        "docs/codexw-self-supervision-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(
        &todos,
        "docs/codexw-background-execution-boundary.md",
        "TODOS.md",
    );
    assert_contains(&todos, "docs/codexw-plugin-system.md", "TODOS.md");
    assert_contains(
        &todos,
        "docs/codexw-plugin-system-implementation-plan.md",
        "TODOS.md",
    );
    assert_contains(&todos, "docs/codexw-workspace-tool-policy.md", "TODOS.md");
    assert_contains(&todos, "docs/codexw-support-claim-checklist.md", "TODOS.md");

    assert_contains(
        &broker_contract,
        "owner",
        "docs/codexw-broker-adapter-contract.md",
    );
    assert_contains(
        &broker_contract,
        "observer",
        "docs/codexw-broker-adapter-contract.md",
    );
    assert_contains(
        &broker_contract,
        "rival",
        "docs/codexw-broker-adapter-contract.md",
    );
    assert_contains(
        &broker_status,
        "supported experimental adapter",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_status,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_status,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "tool_slow",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "tool_wedged",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "observe_or_interrupt",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "interrupt_or_exit_resume",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "warn_only",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "observe_status",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "interrupt_turn",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "exit_and_resume",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "supervision_notice",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "request_id",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "thread_name",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "wrapper_background_shell",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "source_call_id",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "observation_state",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "target_background_shell_reference",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "observed_background_shell_job",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "async_tool_backpressure",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "async_tool_workers",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains_case_insensitive(
        &broker_status,
        "abandoned_after_timeout",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_proof,
        "supported experimental adapter",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains(
        &broker_proof,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains(
        &broker_proof,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "tool_slow",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "tool_wedged",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "observe_or_interrupt",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "interrupt_or_exit_resume",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "warn_only",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "observe_status",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "interrupt_turn",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "exit_and_resume",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "wrapper_background_shell",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "source_call_id",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "target_background_shell_reference",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "observed_background_shell_job",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "async_tool_backpressure",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "async_tool_workers",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "abandoned_after_timeout",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_request_id",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_thread_name",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_source_call_id",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_observation_state",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_output_state",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "oldest_observed_background_shell_job",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_proof,
        "continued observation/output/job visibility",
        "docs/codexw-broker-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "observe_or_interrupt",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "interrupt_or_exit_resume",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "warn_only",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "supervision_notice",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "observe_status",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "interrupt_turn",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "exit_and_resume",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "wrapper_background_shell",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "source_call_id",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "target_background_shell_reference",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "observed_background_shell_job",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "output_state",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "request_id",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "thread_name",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "source_call_id",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "observation_state",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "last_output_age_seconds",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "async_tool_backpressure",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_request_id",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_thread_name",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_source_call_id",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_observation_state",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_output_state",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "oldest_observed_background_shell_job",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "abandoned worker rows",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "async_tool_workers",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains_case_insensitive(
        &broker_event_envelope,
        "abandoned_after_timeout",
        "docs/codexw-broker-event-envelope.md",
    );
    assert_contains(
        &broker_policy,
        "supported experimental adapter",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "project-assignment or dependency-edge surface",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "tool_slow",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "tool_wedged",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "wrapper_background_shell",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "source_call_id",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "target_background_shell_reference",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "wrapper_background_shell_started_no_output_yet",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "no_output_observed_yet",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "observed_background_shell_job",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "last_output_age_seconds",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "async_tool_backpressure",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_policy,
        "async_tool_workers",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_out_of_scope,
        "out of scope",
        "docs/codexw-broker-out-of-scope.md",
    );
    assert_contains_case_insensitive(
        &broker_out_of_scope,
        "project-assignment or dependency-edge contract",
        "docs/codexw-broker-out-of-scope.md",
    );
    assert_contains(
        &broker_endpoint_audit,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-broker-endpoint-audit.md",
    );
    assert_contains(
        &broker_endpoint_audit,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-broker-endpoint-audit.md",
    );
    assert_contains(
        &broker_endpoint_audit,
        "session-scoped artifact index/detail/content",
        "docs/codexw-broker-endpoint-audit.md",
    );
    assert_contains(
        &broker_endpoint_audit,
        "session-scoped project assignment",
        "docs/codexw-broker-endpoint-audit.md",
    );
    assert_contains(
        &broker_endpoint_audit,
        "project dependency edges",
        "docs/codexw-broker-endpoint-audit.md",
    );
    assert_contains(
        &broker_hardening,
        "not a blocker",
        "docs/codexw-broker-hardening-catalog.md",
    );
    assert_contains_case_insensitive(
        &broker_hardening,
        "artifact-centric consumer story",
        "docs/codexw-broker-hardening-catalog.md",
    );
    assert_contains_case_insensitive(
        &broker_decision,
        "broker-backed clients such as app and webui",
        "docs/codexw-broker-connector-decision.md",
    );
    assert_contains_case_insensitive(
        &broker_decision,
        "artifact index/detail/content",
        "docs/codexw-broker-connector-decision.md",
    );
    assert_contains(
        &broker_promotion,
        "codexw-broker-artifact-contract-sketch.md",
        "docs/codexw-broker-adapter-promotion.md",
    );
    assert_contains_case_insensitive(
        &broker_promotion,
        "artifact index/detail/content routes",
        "docs/codexw-broker-adapter-promotion.md",
    );
    assert_contains(
        &broker_promotion,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-broker-adapter-promotion.md",
    );
    assert_contains_case_insensitive(
        &broker_promotion,
        "project-assignment and dependency-edge routes",
        "docs/codexw-broker-adapter-promotion.md",
    );
    assert_contains(
        &broker_mapping,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-broker-connector-mapping.md",
    );
    assert_contains_case_insensitive(
        &broker_mapping,
        "any artifact index/detail/content route",
        "docs/codexw-broker-connector-mapping.md",
    );
    assert_contains_case_insensitive(
        &broker_mapping,
        "project-assignment or dependency-edge route",
        "docs/codexw-broker-connector-mapping.md",
    );
    assert_contains_case_insensitive(
        &broker_compat_target,
        "app/webui",
        "docs/codexw-broker-compatibility-target.md",
    );
    assert_contains_case_insensitive(
        &broker_compat_target,
        "host shell examination",
        "docs/codexw-broker-compatibility-target.md",
    );
    assert_contains(
        &broker_compat_target,
        "codexw-broker-artifact-contract-sketch.md",
        "docs/codexw-broker-compatibility-target.md",
    );
    assert_contains_case_insensitive(
        &broker_adapter_plan,
        "host examination shell-first",
        "docs/codexw-broker-connector-adapter-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_adapter_plan,
        "artifact index/detail/content",
        "docs/codexw-broker-connector-adapter-plan.md",
    );
    assert_contains(
        &broker_adapter_plan,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-broker-connector-adapter-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_shared_assumptions,
        "broker-backed app/webui clients",
        "docs/codexw-broker-shared-assumptions.md",
    );
    assert_contains_case_insensitive(
        &broker_shared_assumptions,
        "dedicated artifact catalog",
        "docs/codexw-broker-shared-assumptions.md",
    );
    assert_contains_case_insensitive(
        &broker_session_identity,
        "broker-backed app/webui clients",
        "docs/codexw-broker-session-identity.md",
    );
    assert_contains_case_insensitive(
        &broker_session_identity,
        "artifact entries",
        "docs/codexw-broker-session-identity.md",
    );
    assert_contains_case_insensitive(
        &broker_client_policy,
        "shell-first host-examination posture",
        "docs/codexw-broker-client-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_client_policy,
        "artifact surface exists",
        "docs/codexw-broker-client-policy.md",
    );
    assert_contains_case_insensitive(
        &broker_client_policy,
        "project-assignment or dependency-edge collaboration surface exists",
        "docs/codexw-broker-client-policy.md",
    );

    assert_contains_case_insensitive(
        &native_boundaries,
        "alternate-screen",
        "docs/codexw-native-support-boundaries.md",
    );
    assert_contains_case_insensitive(
        &native_boundaries,
        "audio",
        "docs/codexw-native-support-boundaries.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "terminal-first",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "scrollback-first",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "self-supervision",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "plugin-first",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "async shell-tool",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "tool_slow",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "tool_wedged",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "observe_or_interrupt",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "interrupt_or_exit_resume",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "warn_only",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "observe_status",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "prompt action/policy semantics",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "interrupt_turn",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "exit_and_resume",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "runtime-enforced local failure path",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "supervision notice",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "dedicated wrapper worker threads",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "async_tool_backpressure",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "backlog `recovery_options`",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "backlog `recommended_action`",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "async_tool_workers",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "abandoned_after_timeout",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "output_state",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "last_output_age_seconds",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "source call id",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "request_id",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "inline prompt status",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        ":interrupt",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "backlog-only",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "thread_name",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        ":status",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "automation_ready=false",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "observation_state",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "jobid",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "@capability",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "target_background_shell_reference",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_request_id",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_thread_name",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_source_call_id",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_observation_state",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_output_state",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest_observed_background_shell_job",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "oldest original async request",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "failure_kind=async_tool_backpressure",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "backpressure object",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "retained observation/output visibility",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_status,
        "next-check",
        "docs/codexw-native-product-status.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "terminal-first",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "scrollback-first",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "terminal-first",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "scrollback-first",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "self-supervision",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "plugin-first",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "async shell-tool",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "tool_slow",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "tool_wedged",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "observe_or_interrupt",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "interrupt_or_exit_resume",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        ":status",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        ":interrupt",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "prompt-line action/policy semantics",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "resume",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "async_tool_backpressure",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "backlog `recovery_options`",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "backlog `recommended_action`",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "wrapper-owned",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "command/exec",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "source call id",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "prompt",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "jobid",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "@capability",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "target_background_shell_reference",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "wrapper_background_shell_started_no_output_yet",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &background_execution_boundary,
        "no_output_observed_yet",
        "docs/codexw-background-execution-boundary.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "wrapper_background_shell_streaming_output",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(&self_supervision, "bg-*", "docs/codexw-self-supervision.md");
    assert_contains_case_insensitive(
        &self_supervision,
        "jobid",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "@capability",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "target_background_shell_reference",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "wrapper_background_shell_streaming_output",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "warn_only",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "observe_status",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "interrupt_turn",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "exit_and_resume",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "runtime-enforced local failure path",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "supervision-notice",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "async_tool_backpressure",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "async_tool_workers",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "abandoned_after_timeout",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "output_state",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "last_output_age_seconds",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "source call id",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "jobid",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "@capability",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "target_background_shell_reference",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "oldest_source_call_id",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "oldest_observation_state",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "oldest_output_state",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "oldest_observed_background_shell_job",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "failure_kind=async_tool_backpressure",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "backpressure",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "retain `observation_state`",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_policy,
        "next-check",
        "docs/codexw-native-support-policy.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "tool_slow",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "tool_wedged",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "observe_or_interrupt",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "interrupt_or_exit_resume",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "warn_only",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "observe_status",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "interrupt_turn",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "exit_and_resume",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "runtime-enforced local failure path",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "supervision_notice",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "async_tool_backpressure",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "`recovery_policy`, and `recovery_options`",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "backlog `recommended_action`",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "async_tool_workers",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_proof,
        "abandoned_after_timeout",
        "docs/codexw-native-proof-matrix.md",
    );
    assert_contains_case_insensitive(
        &native_hardening,
        "not currently a blocker",
        "docs/codexw-native-hardening-catalog.md",
    );
    assert_contains_case_insensitive(
        &self_evolution,
        "safely hands off to a newer binary",
        "docs/codexw-self-evolution.md",
    );
    assert_contains_case_insensitive(
        &self_evolution,
        "checkpoint",
        "docs/codexw-self-evolution.md",
    );
    assert_contains_case_insensitive(
        &self_evolution,
        "standalone local-runtime-first",
        "docs/codexw-self-evolution.md",
    );
    assert_contains_case_insensitive(
        &self_evolution,
        "plugin-aware",
        "docs/codexw-self-evolution.md",
    );
    assert_contains_case_insensitive(
        &self_evolution_plan,
        "resume-handoff",
        "docs/codexw-self-evolution-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_evolution_plan,
        "old process does not exit before acknowledgment",
        "docs/codexw-self-evolution-implementation-plan.md",
    );
    assert_contains_case_insensitive(&self_evolution, "git repo", "docs/codexw-self-evolution.md");
    assert_contains_case_insensitive(
        &self_evolution_plan,
        "git pull",
        "docs/codexw-self-evolution-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_evolution_plan,
        "plugin versus core decision policy",
        "docs/codexw-self-evolution-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "no `codexw` tool use or shell exec should be allowed to hang the runtime indefinitely",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "standalone local-runtime-first",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "background-shell dynamic tools must not execute in a way that freezes the input loop indefinitely",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "tool_slow",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "tool_wedged",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "observe_or_interrupt",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "interrupt_or_exit_resume",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "warn_only",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "supervision_notice",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "observe_status",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "interrupt_turn",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "exit_and_resume",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "automation_ready=false",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "hard runtime limit",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "dedicated wrapper worker threads",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "async_tool_backpressure",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "structured backpressure object carrying",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "explicit `recovery_options`",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "explicit `recommended_action`",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "compact action/policy semantics",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "async_tool_workers",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "abandoned_after_timeout",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "abandoned async",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "recent_output_observed",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "stale_output_observed",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "last_output_age_seconds",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "source call id",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "inline prompt status",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "resume",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "abandoned backlog",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "abandoned backlog",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest_observation_state",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest_output_state",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest_request_id",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest_thread_name",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest_observed_background_shell_job",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "oldest original request",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "failure_kind=async_tool_backpressure",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "backpressure object",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "still observable after timeout",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "next check",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "request_id",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "thread_name",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        ":status",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "source_call_id",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision,
        "observation_state",
        "docs/codexw-self-supervision.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "background-shell dynamic tools",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "plugin-first",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "tool_slow",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "tool_wedged",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "observe_or_interrupt",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "interrupt_or_exit_resume",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "warn_only",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "supervision_notice",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "observe_status",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "interrupt_turn",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "exit_and_resume",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "fails an overdue request locally",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "async_tool_backpressure",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "async_tool_workers",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "abandoned_after_timeout",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "dedicated wrapper worker threads",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "recent_output_observed",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "stale_output_observed",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "source call id",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "abandoned backlog",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "oldest_observation_state",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "oldest_output_state",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "oldest_observed_background_shell_job",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "failure_kind=async_tool_backpressure",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "backpressure object",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "still carry current `observation_state`",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &self_supervision_plan,
        "next planned health check horizon",
        "docs/codexw-self-supervision-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "observe_or_interrupt",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "interrupt_or_exit_resume",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "warn_only",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "operator_interrupt_or_exit_resume",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "supervision_notice",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "request_id",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "thread_name",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "observe_status",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "interrupt_turn",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "exit_and_resume",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "async_tool_backpressure",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "`recovery_policy`, and `recovery_options`",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "backlog `recommended_action`",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "async_tool_workers",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "abandoned_after_timeout",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "output_state",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "target_background_shell_reference",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "observed_background_shell_job",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_request_id",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_thread_name",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_source_call_id",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_observation_state",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_output_state",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_observed_background_shell_job",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "oldest_target_background_shell_reference",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &local_api_event_sourcing,
        "last_output_age_seconds",
        "docs/codexw-local-api-event-sourcing.md",
    );
    assert_contains_case_insensitive(
        &plugin_system,
        "voice reminder over the host speaker",
        "docs/codexw-plugin-system.md",
    );
    assert_contains_case_insensitive(
        &plugin_system,
        "https://github.com/lzbgt/codexw-plugins",
        "docs/codexw-plugin-system.md",
    );
    assert_contains_case_insensitive(
        &plugin_system,
        "self-evolution",
        "docs/codexw-plugin-system.md",
    );
    assert_contains_case_insensitive(
        &plugin_system_plan,
        "trusted-source checks",
        "docs/codexw-plugin-system-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &plugin_system_plan,
        "plugin install/update over full core replacement",
        "docs/codexw-plugin-system-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "app/webui",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "host shell",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "workspace dynamic tools",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "cross-deployment",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "artifact catalog",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "shell-first",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "usable with caveat",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "tool_slow",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "wrapper_background_shell_started_no_output_yet",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "no_output_observed_yet",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "observed_background_shell_job",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "async_tool_workers",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_host_matrix,
        "not part of the current supported experimental adapter",
        "docs/codexw-broker-host-examination-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "sibling `~/work/agent` workspace",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "supported for documented experimental use",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "shell-first",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "artifact list/detail/content api",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "tool_slow",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "wrapper_background_shell",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "source_call_id",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "target_background_shell_reference",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "wrapper_background_shell_started_no_output_yet",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "no_output_observed_yet",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "observed_background_shell_job",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "last_output_age_seconds",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "async_tool_backpressure",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &broker_handoff,
        "async_tool_workers",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-deployment-collaboration.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-project-dependency-collaboration.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-project-dependency-implementation-plan.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-deployment-handoff-contract-sketch.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains(
        &broker_handoff,
        "codexw-cross-deployment-handoff-implementation-plan.md",
        "docs/codexw-broker-integration-handoff.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment,
        "work handoff",
        "docs/codexw-cross-deployment-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment,
        "session-scoped",
        "docs/codexw-cross-deployment-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment,
        "broker-mediated",
        "docs/codexw-cross-deployment-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment,
        "may not coexist on one host",
        "docs/codexw-cross-deployment-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment,
        "artifact-contract gap",
        "docs/codexw-cross-deployment-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_project_dependency,
        "projects may depend on one another",
        "docs/codexw-cross-project-dependency-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_project_dependency,
        "broker-mediated",
        "docs/codexw-cross-project-dependency-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_project_dependency,
        "dependency edge",
        "docs/codexw-cross-project-dependency-collaboration.md",
    );
    assert_contains_case_insensitive(
        &cross_project_contract,
        "session_project_bound",
        "docs/codexw-cross-project-dependency-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_project_contract,
        "project_dependency_declared",
        "docs/codexw-cross-project-dependency-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_project_contract,
        "session-to-project assignment",
        "docs/codexw-cross-project-dependency-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_project_plan,
        "dependency-edge create/list/detail routes",
        "docs/codexw-cross-project-dependency-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_project_plan,
        "handoff creation can reference dependency ids",
        "docs/codexw-cross-project-dependency-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_project_plan,
        "do not assume the participating deployments share a host",
        "docs/codexw-cross-project-dependency-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_contract,
        "handoff record",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_contract,
        "source.project_id",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_contract,
        "dependency_refs",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_contract,
        "session_handoff_proposed",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_contract,
        "artifact api",
        "docs/codexw-cross-deployment-handoff-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_plan,
        "accept/decline/complete",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_plan,
        "target project identity",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_plan,
        "same-host",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_plan,
        "route family exists",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &cross_deployment_plan,
        "do not fake handoff",
        "docs/codexw-cross-deployment-handoff-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_client_fixture,
        "shell-first host examination",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains_case_insensitive(
        &broker_client_fixture,
        "artifact index/detail/content route family",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_client_fixture,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_client_fixture,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_contract,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-broker-adapter-contract.md",
    );
    assert_contains(
        &broker_contract,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-broker-adapter-contract.md",
    );
    assert_contains(
        &local_api_sketch,
        "docs/codexw-broker-integration-handoff.md",
        "docs/codexw-local-api-sketch.md",
    );
    assert_contains_case_insensitive(
        &local_api_sketch,
        "shell-first",
        "docs/codexw-local-api-sketch.md",
    );
    assert_contains_case_insensitive(
        &local_api_sketch,
        "supported experimental adapter",
        "docs/codexw-local-api-sketch.md",
    );
    assert_contains(
        &local_api_plan,
        "docs/codexw-broker-integration-handoff.md",
        "docs/codexw-local-api-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &local_api_plan,
        "shell-first",
        "docs/codexw-local-api-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &local_api_plan,
        "supported experimental adapter",
        "docs/codexw-local-api-implementation-plan.md",
    );
    assert_contains(
        &local_api_route_matrix,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-local-api-route-matrix.md",
    );
    assert_contains_case_insensitive(
        &local_api_route_matrix,
        "artifact list/detail/content api",
        "docs/codexw-local-api-route-matrix.md",
    );
    assert_contains_case_insensitive(
        &local_api_route_matrix,
        "supported experimental adapter",
        "docs/codexw-local-api-route-matrix.md",
    );
    assert_contains_case_insensitive(
        &local_api_route_matrix,
        "future project/dependency collaboration track",
        "docs/codexw-local-api-route-matrix.md",
    );
    assert_contains(
        &local_api_route_matrix,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-local-api-route-matrix.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "shell-first",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_client_arch,
        "supported experimental adapter",
        "docs/codexw-broker-client-architecture.md",
    );
    assert_contains_case_insensitive(
        &broker_shared_assumptions,
        "supported experimental adapter",
        "docs/codexw-broker-shared-assumptions.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_sketch,
        "artifact index",
        "docs/codexw-broker-artifact-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_sketch,
        "artifact detail",
        "docs/codexw-broker-artifact-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_sketch,
        "shell-first",
        "docs/codexw-broker-artifact-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_sketch,
        "supported experimental adapter",
        "docs/codexw-broker-artifact-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_sketch,
        "design-only",
        "docs/codexw-broker-artifact-contract-sketch.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_plan,
        "artifact index route",
        "docs/codexw-broker-artifact-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_plan,
        "artifact detail route",
        "docs/codexw-broker-artifact-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_plan,
        "do not implement the content route",
        "docs/codexw-broker-artifact-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_plan,
        "support-level gate",
        "docs/codexw-broker-artifact-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &broker_artifact_plan,
        "standalone fixture proof",
        "docs/codexw-broker-artifact-implementation-plan.md",
    );
    assert_contains_case_insensitive(
        &workspace_policy,
        "shell or python",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains_case_insensitive(
        &workspace_policy,
        "no longer advertise",
        "docs/codexw-workspace-tool-policy.md",
    );

    assert_contains(
        &checklist,
        "codexw-broker-adapter-contract.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-adapter-status.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-out-of-scope.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-proof-matrix.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-host-examination-matrix.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-integration-handoff.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-client-architecture.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-compatibility-target.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-connector-decision.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-connector-mapping.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-session-identity.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-client-policy.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-artifact-contract-sketch.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-cross-project-dependency-contract-sketch.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-cross-project-dependency-implementation-plan.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-artifact-implementation-plan.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-broker-hardening-catalog.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-native-support-boundaries.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-native-product-status.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-native-proof-matrix.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &checklist,
        "codexw-native-hardening-catalog.md",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains_case_insensitive(
        &checklist,
        "broker-backed app/webui clients",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains_case_insensitive(
        &checklist,
        "fixture docs still describe shell-first host examination",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains_case_insensitive(
        &checklist,
        "artifact sketch/plan/host-examination docs still say",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains_case_insensitive(
        &checklist,
        "project-assignment and dependency-edge route family",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains_case_insensitive(
        &checklist,
        "sibling `~/work/agent` workspace",
        "docs/codexw-support-claim-checklist.md",
    );
}

#[test]
fn broker_and_native_docs_link_to_automated_support_claim_guard() {
    let checklist = read_repo_file("docs/codexw-support-claim-checklist.md");
    let broker_proof = read_repo_file("docs/codexw-broker-proof-matrix.md");
    let native_proof = read_repo_file("docs/codexw-native-proof-matrix.md");

    for contents in [&checklist, &broker_proof, &native_proof] {
        assert_contains(contents, "wrapper/tests/doc_consistency.rs", "doc text");
    }
}

#[test]
fn design_doc_keeps_workspace_tool_policy_note_linked() {
    let design = read_repo_file("docs/codexw-design.md");
    let workspace_policy = read_repo_file("docs/codexw-workspace-tool-policy.md");
    let readme = read_repo_file("README.md");

    assert_contains(
        &design,
        "codexw-workspace-tool-policy.md",
        "docs/codexw-design.md",
    );
    assert_contains(
        &workspace_policy,
        "workspace_read_file",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "workspace_search_text",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "shell is the general-purpose execution substrate",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "bounded compatibility scan budget",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "legacy workspace compatibility failure",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "transcript and history summaries",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(
        &workspace_policy,
        "legacy workspace compatibility path",
        "docs/codexw-workspace-tool-policy.md",
    );
    assert_contains(&readme, "legacy workspace compatibility path", "README.md");
}

#[test]
fn broker_docs_preserve_fixture_diversity_claims() {
    let readme = read_repo_file("README.md");
    let broker_status = read_repo_file("docs/codexw-broker-adapter-status.md");
    let broker_fixture = read_repo_file("docs/codexw-broker-client-fixture.md");
    let broker_promotion = read_repo_file("docs/codexw-broker-promotion-recommendation.md");
    let broker_support_policy = read_repo_file("docs/codexw-broker-support-policy.md");
    let broker_hardening = read_repo_file("docs/codexw-broker-hardening-catalog.md");
    let checklist = read_repo_file("docs/codexw-support-claim-checklist.md");

    assert_contains(
        &broker_status,
        "Python and Node",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_status,
        "scripts/codexw_broker_client.py",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_status,
        "scripts/codexw_broker_client_node.mjs",
        "docs/codexw-broker-adapter-status.md",
    );

    assert_contains(
        &broker_fixture,
        "scripts/codexw_broker_client.py",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "scripts/codexw_broker_client_node.mjs",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "supervision_notice",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "`recommended_action`, `recovery_policy`, and `recovery_options`",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "oldest_request_id",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "Python-driven supervision workflow",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_fixture,
        "Node-driven supervision workflow",
        "docs/codexw-broker-client-fixture.md",
    );
    assert_contains(
        &broker_status,
        "connector-layer SSE framing proof",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_status,
        "standalone Python and Node fixture workflows",
        "docs/codexw-broker-adapter-status.md",
    );
    assert_contains(
        &broker_support_policy,
        "standalone Python and Node broker fixtures",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains(
        &broker_support_policy,
        "documented `status.updated`, `supervision_notice`, or",
        "docs/codexw-broker-support-policy.md",
    );
    assert_contains(
        &broker_promotion,
        "Python and Node fixtures",
        "docs/codexw-broker-promotion-recommendation.md",
    );
    assert_contains(
        &broker_promotion,
        "status.updated",
        "docs/codexw-broker-promotion-recommendation.md",
    );
    assert_contains(
        &checklist,
        "enriched `status.updated` replay",
        "docs/codexw-support-claim-checklist.md",
    );
    assert_contains(
        &readme,
        "Those standalone Python and Node fixtures now also prove enriched",
        "README.md",
    );

    assert_contains(
        &broker_hardening,
        "Python and Node fixtures",
        "docs/codexw-broker-hardening-catalog.md",
    );
    assert_contains(
        &checklist,
        "Python and Node",
        "docs/codexw-support-claim-checklist.md",
    );
}

#[test]
fn broker_and_native_support_docs_keep_current_support_level_wording() {
    let broker_status = read_repo_file("docs/codexw-broker-adapter-status.md");
    let broker_promotion = read_repo_file("docs/codexw-broker-adapter-promotion.md");
    let broker_recommendation = read_repo_file("docs/codexw-broker-promotion-recommendation.md");
    let broker_policy = read_repo_file("docs/codexw-broker-support-policy.md");
    let native_status = read_repo_file("docs/codexw-native-product-status.md");
    let native_recommendation = read_repo_file("docs/codexw-native-product-recommendation.md");
    let native_policy = read_repo_file("docs/codexw-native-support-policy.md");

    for (name, contents) in [
        ("docs/codexw-broker-adapter-status.md", &broker_status),
        ("docs/codexw-broker-adapter-promotion.md", &broker_promotion),
        (
            "docs/codexw-broker-promotion-recommendation.md",
            &broker_recommendation,
        ),
        ("docs/codexw-broker-support-policy.md", &broker_policy),
    ] {
        assert_contains(contents, "supported experimental adapter", name);
    }

    assert_contains_case_insensitive(
        &broker_recommendation,
        "project-assignment or dependency-edge route family",
        "docs/codexw-broker-promotion-recommendation.md",
    );

    for (name, contents) in [
        ("docs/codexw-native-product-status.md", &native_status),
        (
            "docs/codexw-native-product-recommendation.md",
            &native_recommendation,
        ),
        ("docs/codexw-native-support-policy.md", &native_policy),
    ] {
        assert_contains_case_insensitive(contents, "terminal-first", name);
        assert_contains_case_insensitive(contents, "scrollback-first", name);
    }
}
